### ISSUE TITLE
Exceptions in libhfst.py

### ISSUE THREAD

**Issue by hfst-importer** [hfst/hfst#169]
I am trying to use python3 exception mechanism to get the best available language automata:
```~~
    try:
        if path:
            res = libhfst.HfstTransducer(libhfst.HfstInputStream(path))
        else:
            res = libhfst.HfstTransducer(libhfst.HfstInputStream("/usr/local/share/fi/morphology.omor.hfst"))
    except OSError:
```~~
Resulting exception cannot be caught or handled:
```~~
    Traceback (most recent call last):
    File "src/scripts/omorfi.py", line 101, in load_omorfi
        res = libhfst.HfstTransducer(libhfst.HfstInputStream("/usr/local/share/fi/morphology.omor.hfst"))
    File "/usr/local/lib/python3.2/dist-packages/libhfst.py", line 1493, in __init__
        this = _libhfst.new_HfstInputStream(*args)
    SystemError: exception <class 'libhfst.NotTransducerStreamException'> not a BaseException subclass
```~~


Reported by: flammie

**Comment by eaxelson** [comment]
The Python API has been rewritten, so closing this issue.
